project_id = "jcagwttulyacdehtkocs"

[functions.ai-tool]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.ai-company]
verify_jwt = true